### ISSUE TITLE
Exception NoMethodError -> undefined method `ttr' for nil:NilClass

### ISSUE THREAD

**Issue by supremoUL** [nesquena/backburner#175]
For some unknown reason this error is occurring continuously, when I switched my worker type from simple to threadsonfork.

It is running on centos 7. There is a possible suspicion that beanstalkd was restarted and after that this error is coming continuously. Here is the backtrace -
```
E, [2022-02-21T20:38:06.617936 #64916] ERROR -- : Exception NoMethodError -> undefined method `ttr' for nil:NilClass
   vendor/ruby/2.3.0/gems/beaneater-1.0.0/lib/beaneater/job/record.rb:157:in `ttr'
   vendor/ruby/2.3.0/gems/backburner-1.2.0/lib/backburner/job.rb:54:in `block in process'
   vendor/ruby/2.3.0/gems/backburner-1.2.0/lib/backburner/hooks.rb:28:in `block in around_hook_events'
   vendor/ruby/2.3.0/gems/backburner-1.2.0/lib/backburner/hooks.rb:37:in `around_hook_events'
   vendor/ruby/2.3.0/gems/backburner-1.2.0/lib/backburner/job.rb:48:in `process'
   vendor/ruby/2.3.0/gems/backburner-1.2.0/lib/backburner/worker.rb:135:in `work_one_job'
   vendor/ruby/2.3.0/gems/backburner-1.2.0/lib/backburner/workers/threads_on_fork.rb:212:in `run_while_can'
   vendor/ruby/2.3.0/gems/backburner-1.2.0/lib/backburner/workers/threads_on_fork.rb:188:in `fork_inner'
   vendor/ruby/2.3.0/gems/backburner-1.2.0/lib/backburner/workers/threads_on_fork.rb:164:in `block in fork_tube'
   vendor/ruby/2.3.0/gems/backburner-1.2.0/lib/backburner/workers/threads_on_fork.rb:252:in `block in fork_it'
   vendor/ruby/2.3.0/gems/backburner-1.2.0/lib/backburner/workers/threads_on_fork.rb:249:in `fork'
   vendor/ruby/2.3.0/gems/backburner-1.2.0/lib/backburner/workers/threads_on_fork.rb:249:in `fork_it'
   vendor/ruby/2.3.0/gems/backburner-1.2.0/lib/backburner/workers/threads_on_fork.rb:163:in `fork_tube'
   vendor/ruby/2.3.0/gems/backburner-1.2.0/lib/backburner/workers/threads_on_fork.rb:150:in `block in fork_and_watch'
```
Any suggestion for this issue will be highly appreciated.

**Comment by nesquena** [comment]
Sorry to hear that it isn't working due to that nil error. 

I don't think I've seen this error before, so I can't easily speak to it. If anyone can figure out what might be going wrong here, I'd be happy to merge any PRs as a result.
